### PR TITLE
Fixed issue #136 and implement new feature #137

### PR DESCRIPTION
**Pull request by llaville**
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/composer-unused/symbol-parser/blob/main/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/composer-unused/symbol-parser/pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

See issue #136 and new feature #137 for all other explains

### CODE REVIEW

**Comment by llaville** [comment]
@icanhazstring Time for review. No pressure ;-)

**Comment by llaville** [comment]
FYI : latest operation with ref https://github.com/composer-unused/symbol-parser/commit/d3e64288ce72faac7bd2cd69e01a55a3835ab006 is a squash commit and rebase with main branch

**Comment by llaville** [comment]
@icanhazstring Could you think to change properties visibility (https://github.com/composer-unused/symbol-parser/blob/0.2.2/src/Parser/PHP/ConsumedSymbolCollector.php#L24-L26) from private to protected.
As the class is not final, it may be useful to extends it and retrieve strategies easily with protected properties.

**Comment by llaville** [comment]
@icanhazstring Did you choose a decision concerning this PR.
Merge in state or not ?

**Comment by icanhazstring** [comment]
Done 🙂

**Pull request merged**
